export enum FilterTypes {
    VEHICLE_MODEL = 'VEHICLE_MODEL',
    ZONE_AREA = 'ZONE_AREA',
    BUS_LANE_TYPE = 'BUS_LANE_TYPE',
    OBJECT_TYPE = 'OBJECT_TYPE',
    POI_CATEGORY = 'POI_CATEGORY',
    VEHICLE_STATUS = 'VEHICLE_STATUS',
    VEHICLE_TYPE = 'VEHICLE_TYPE',
}